__all__ = ["bidEvaluator", 
           "riskAware", 
           "straightMU", 
           "straightMV", 
           "targetMU", 
           "targetMV", 
           "targetMUS", 
           "targetMVS", 
           "targetPrice", 
           "targetPriceDist"]